global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#promethus-alert'
    send_resolved: true
~

