global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['52.221.190.106:9093']
rule_files:
  - rules.yml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['52.221.190.106:9100']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['52.221.190.106:9093']
~
~

